/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'donald' at '17-12-11 下午10:26' with Gradle 3.1
 *
 * @author donald, @date 17-12-11 下午10:26
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
